"""SQLAlchemy base classes and shared column types."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

__all__ = ["Base", "TimestampMixin", "uuid_pk", "utcnow", "EncryptedText"]

# Explicit naming conventions so that Alembic generates stable, predictable
# constraint names. Without them, autogenerated migrations produce
# database-assigned names that differ between environments, and a later
# migration that needs to drop a constraint by name fails in exactly one of
# them -- usually production.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def __repr__(self) -> str:
        """A repr that never renders column values.

        Every model here is one join away from taxpayer data, and a default
        SQLAlchemy repr in a traceback or a debugger session would print it.
        Showing only the identity keeps debugging usable without turning a
        stack trace into a disclosure.
        """
        identifier = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identifier}>"


def utcnow() -> datetime:
    return datetime.now(UTC)


def uuid_pk() -> Mapped[str]:
    """A UUID primary key.

    UUIDs rather than sequential integers: a sequential return id in a URL
    tells an attacker exactly what to try next, and tells anyone who sees one
    how many returns the company has processed. Object-level authorization is
    still enforced on every request -- unguessable ids are a speed bump, not
    an access control -- but they remove the trivial enumeration path.
    """
    return mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class EncryptedText(String):
    """Marker type for columns holding ciphertext from ``FieldCipher``.

    Functionally a ``String``: encryption happens in the service layer, not in
    a type decorator, because the cipher needs a per-row context string
    (``taxpayer:<id>.ssn``) that a column type cannot see. The marker exists so
    that ``grep EncryptedText`` lists every encrypted column, which is the
    question a security review actually asks.
    """

    def __init__(self, length: int = 1024, **kwargs: Any) -> None:
        super().__init__(length, **kwargs)
