"""initial schema

Revision ID: 8daf566cf68e
Revises: 
Create Date: 2026-09-02 03:36:04.430230+00:00
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '8daf566cf68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('SUPER_ADMIN','TAX_ADMIN','SUPPORT','SECURITY_ADMIN','FINANCE','READ_ONLY')", name=op.f('ck_admin_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('admin_user_id', sa.String(length=36), nullable=True),
    sa.Column('tax_return_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_admin_user_id'), 'audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tax_return_id'), 'audit_logs', ['tax_return_id'], unique=False)
    op.create_index('ix_audit_logs_type_time', 'audit_logs', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_user_time', 'audit_logs', ['user_id', 'occurred_at'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('INFO','LOW','MEDIUM','HIGH','CRITICAL')", name=op.f('ck_security_events_severity_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_security_events'))
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_ip_hash'), 'security_events', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_security_events_occurred_at'), 'security_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_severity'), 'security_events', ['severity'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secret_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_recovery_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','DELETION_REQUESTED','ANONYMIZED')", name=op.f('ck_users_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('rule_set_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction', sa.String(length=16), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('certification', sa.String(length=16), nullable=False),
    sa.Column('approved_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=False),
    sa.Column('regression_suite_passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("certification IN ('DRAFT','UNDER_REVIEW','PRODUCTION')", name=op.f('ck_rule_set_approvals_certification_valid')),
    sa.ForeignKeyConstraint(['approved_by_admin_id'], ['admin_users.id'], name=op.f('fk_rule_set_approvals_approved_by_admin_id_admin_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_set_approvals')),
    sa.UniqueConstraint('jurisdiction', 'tax_year', 'rule_version', name='rule_version_unique')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_satisfied', sa.Boolean(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_user_active', 'sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('taxpayers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_initial', sa.String(length=1), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('ssn_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('ssn_last_four', sa.String(length=4), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=64), nullable=False),
    sa.Column('address_line2', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('is_us_citizen_or_resident', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_taxpayers_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxpayers'))
    )
    op.create_index(op.f('ix_taxpayers_user_id'), 'taxpayers', ['user_id'], unique=False)
    op.create_table('tax_returns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('taxpayer_id', sa.String(length=36), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('files_federal', sa.Boolean(), nullable=False),
    sa.Column('files_oklahoma', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayers.id'], name=op.f('fk_tax_returns_taxpayer_id_taxpayers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tax_returns_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_returns')),
    sa.UniqueConstraint('user_id', 'tax_year', name='one_return_per_user_year')
    )
    op.create_index(op.f('ix_tax_returns_user_id'), 'tax_returns', ['user_id'], unique=False)
    op.create_index('ix_tax_returns_user_year', 'tax_returns', ['user_id', 'tax_year'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processor_name', sa.String(length=32), nullable=False),
    sa.Column('processor_reference', sa.String(length=128), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=16), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PAID','FAILED','REFUNDED')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], name=op.f('fk_payments_tax_return_id_tax_returns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_processor_reference'), 'payments', ['processor_reference'], unique=False)
    op.create_index(op.f('ix_payments_tax_return_id'), 'payments', ['tax_return_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('support_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_admin_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','WAITING_ON_CUSTOMER','ESCALATED','RESOLVED','CLOSED')", name=op.f('ck_support_cases_status_valid')),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admin_users.id'], name=op.f('fk_support_cases_assigned_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], name=op.f('fk_support_cases_tax_return_id_tax_returns')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_cases_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_cases'))
    )
    op.create_index(op.f('ix_support_cases_user_id'), 'support_cases', ['user_id'], unique=False)
    op.create_table('tax_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('malware_scan_status', sa.String(length=16), nullable=False),
    sa.Column('malware_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extraction_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('PENDING','COMPLETE','FAILED','NOT_APPLICABLE')", name=op.f('ck_tax_documents_extraction_status_valid')),
    sa.CheckConstraint("malware_scan_status IN ('PENDING','CLEAN','INFECTED','FAILED')", name=op.f('ck_tax_documents_scan_status_valid')),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], name=op.f('fk_tax_documents_tax_return_id_tax_returns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tax_documents_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_documents'))
    )
    op.create_index(op.f('ix_tax_documents_tax_return_id'), 'tax_documents', ['tax_return_id'], unique=False)
    op.create_index(op.f('ix_tax_documents_user_id'), 'tax_documents', ['user_id'], unique=False)
    op.create_table('tax_return_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('return_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','VALIDATED','READY_FOR_FILING','SUBMITTED','ACCEPTED','REJECTED','SUPERSEDED')", name=op.f('ck_tax_return_versions_status_valid')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_tax_return_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['supersedes_version_id'], ['tax_return_versions.id'], name=op.f('fk_tax_return_versions_supersedes_version_id_tax_return_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tax_return_id'], ['tax_returns.id'], name=op.f('fk_tax_return_versions_tax_return_id_tax_returns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_return_versions')),
    sa.UniqueConstraint('tax_return_id', 'version_number', name='version_number_unique')
    )
    op.create_index(op.f('ix_tax_return_versions_tax_return_id'), 'tax_return_versions', ['tax_return_id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_version_id', sa.String(length=36), nullable=True),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('document_version', sa.String(length=32), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tax_return_version_id'], ['tax_return_versions.id'], name=op.f('fk_consents_tax_return_version_id_tax_return_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('document_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('verified_by_user', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_document_extractions_confidence_range')),
    sa.ForeignKeyConstraint(['document_id'], ['tax_documents.id'], name=op.f('fk_document_extractions_document_id_tax_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_extractions'))
    )
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=False)
    op.create_table('sensitive_data_accesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('field_accessed', sa.String(length=64), nullable=False),
    sa.Column('justification', sa.String(length=512), nullable=False),
    sa.Column('support_case_id', sa.String(length=36), nullable=True),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], name=op.f('fk_sensitive_data_accesses_admin_user_id_admin_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['support_case_id'], ['support_cases.id'], name=op.f('fk_sensitive_data_accesses_support_case_id_support_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensitive_data_accesses'))
    )
    op.create_index(op.f('ix_sensitive_data_accesses_accessed_at'), 'sensitive_data_accesses', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_sensitive_data_accesses_admin_user_id'), 'sensitive_data_accesses', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_sensitive_data_accesses_user_id'), 'sensitive_data_accesses', ['user_id'], unique=False)
    op.create_table('signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_version_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('signature_method', sa.String(length=32), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('signed_content_sha256', sa.String(length=64), nullable=False),
    sa.Column('spouse_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_select_pin_last_four', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tax_return_version_id'], ['tax_return_versions.id'], name=op.f('fk_signatures_tax_return_version_id_tax_return_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signatures_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signatures'))
    )
    op.create_index(op.f('ix_signatures_tax_return_version_id'), 'signatures', ['tax_return_version_id'], unique=False)
    op.create_table('tax_calculations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('federal_rule_version', sa.String(length=32), nullable=False),
    sa.Column('oklahoma_rule_version', sa.String(length=32), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('federal_agi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_total_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_refund', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_amount_owed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('oklahoma_total_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('oklahoma_refund', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('oklahoma_amount_owed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('oklahoma_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rule_sets_certified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['tax_return_versions.id'], name=op.f('fk_tax_calculations_version_id_tax_return_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_calculations'))
    )
    op.create_index(op.f('ix_tax_calculations_version_id'), 'tax_calculations', ['version_id'], unique=False)
    op.create_table('efile_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tax_return_version_id', sa.String(length=36), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('provider_reference', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('signature_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('MOCK','TEST','LIVE')", name=op.f('ck_efile_submissions_channel_valid')),
    sa.CheckConstraint("jurisdiction IN ('FEDERAL','OK')", name=op.f('ck_efile_submissions_jurisdiction_valid')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_efile_submissions_payment_id_payments')),
    sa.ForeignKeyConstraint(['signature_id'], ['signatures.id'], name=op.f('fk_efile_submissions_signature_id_signatures')),
    sa.ForeignKeyConstraint(['tax_return_version_id'], ['tax_return_versions.id'], name=op.f('fk_efile_submissions_tax_return_version_id_tax_return_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_efile_submissions')),
    sa.UniqueConstraint('submission_id', 'jurisdiction', name='submission_unique')
    )
    op.create_index(op.f('ix_efile_submissions_submission_id'), 'efile_submissions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_efile_submissions_tax_return_version_id'), 'efile_submissions', ['tax_return_version_id'], unique=False)
    op.create_table('efile_acknowledgments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authority_reference', sa.String(length=128), nullable=True),
    sa.Column('rejection_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_payload_reference', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('MOCK','TEST','LIVE')", name=op.f('ck_efile_acknowledgments_channel_valid')),
    sa.CheckConstraint("status <> 'ACCEPTED' OR (channel = 'LIVE' AND authority_reference IS NOT NULL)", name=op.f('ck_efile_acknowledgments_acceptance_requires_live_channel_and_reference')),
    sa.ForeignKeyConstraint(['submission_id'], ['efile_submissions.id'], name=op.f('fk_efile_acknowledgments_submission_id_efile_submissions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_efile_acknowledgments'))
    )
    op.create_index(op.f('ix_efile_acknowledgments_submission_id'), 'efile_acknowledgments', ['submission_id'], unique=False)
    # ### end Alembic commands ###


    _harden_audit_tables()


def _harden_audit_tables() -> None:
    """Make the append-only tables append-only in the database, not just in code.

    The application connects as a role that can INSERT and SELECT on the audit
    and security tables and nothing else. Without this, "the audit log is
    immutable" is a statement about the code we happen to have written, and an
    attacker who reaches SQL execution -- or an engineer under pressure during
    an incident -- can rewrite the record of what happened.

    Runs only when the ``olbostax_app`` role exists, so a developer's local
    database and the test suite are unaffected. Provisioning that role is an
    infrastructure step, documented in infrastructure/README.md.
    """
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'olbostax_app') THEN
                REVOKE UPDATE, DELETE, TRUNCATE
                    ON audit_logs, security_events, sensitive_data_accesses,
                       consents, signatures, efile_acknowledgments
                    FROM olbostax_app;
                GRANT SELECT, INSERT
                    ON audit_logs, security_events, sensitive_data_accesses,
                       consents, signatures, efile_acknowledgments
                    TO olbostax_app;
            END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_efile_acknowledgments_submission_id'), table_name='efile_acknowledgments')
    op.drop_table('efile_acknowledgments')
    op.drop_index(op.f('ix_efile_submissions_tax_return_version_id'), table_name='efile_submissions')
    op.drop_index(op.f('ix_efile_submissions_submission_id'), table_name='efile_submissions')
    op.drop_table('efile_submissions')
    op.drop_index(op.f('ix_tax_calculations_version_id'), table_name='tax_calculations')
    op.drop_table('tax_calculations')
    op.drop_index(op.f('ix_signatures_tax_return_version_id'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_sensitive_data_accesses_user_id'), table_name='sensitive_data_accesses')
    op.drop_index(op.f('ix_sensitive_data_accesses_admin_user_id'), table_name='sensitive_data_accesses')
    op.drop_index(op.f('ix_sensitive_data_accesses_accessed_at'), table_name='sensitive_data_accesses')
    op.drop_table('sensitive_data_accesses')
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_tax_return_versions_tax_return_id'), table_name='tax_return_versions')
    op.drop_table('tax_return_versions')
    op.drop_index(op.f('ix_tax_documents_user_id'), table_name='tax_documents')
    op.drop_index(op.f('ix_tax_documents_tax_return_id'), table_name='tax_documents')
    op.drop_table('tax_documents')
    op.drop_index(op.f('ix_support_cases_user_id'), table_name='support_cases')
    op.drop_table('support_cases')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_tax_return_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_processor_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_tax_returns_user_year', table_name='tax_returns')
    op.drop_index(op.f('ix_tax_returns_user_id'), table_name='tax_returns')
    op.drop_table('tax_returns')
    op.drop_index(op.f('ix_taxpayers_user_id'), table_name='taxpayers')
    op.drop_table('taxpayers')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index('ix_sessions_user_active', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('rule_set_approvals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_severity'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_occurred_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_ip_hash'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_audit_logs_user_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_type_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tax_return_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
